#!/usr/bin/env ruby
# File: script/console
irb = RUBY_PLATFORM =~ /(:?mswin|mingw)/ ? 'irb.bat' : 'irb'

libs =  " -r irb/completion"
libs << " -r riak"
# libs <<  " -r #{File.dirname(__FILE__) + '/../lib/*'}"
exec "#{irb} #{libs} --simple-prompt"
